#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Joel Hulen

# Short bio or description (displayed in the header)
description: Joel is a deeply analytical, personable, and straightforward professional with demonstrated success managing and developing full life-cycle software products while understanding and exceeding customers’ needs. He has over twenty years of experience in IT, with the majority of that time spent developing software for a variety of businesses. When he's not working full-time at NASA's Jet Propulsion Laboratory (JPL), he's either working on several development projects on the side for his own business as well as App vNext (founded by industry veteran, Carl Franklin), or playing with his 5 kids so they don't destroy the house (or each other).  Joel is enthusiastic about constantly learning new technologies, techniques, and tools in order to improve his skill set. He's always ready to geek out over shiny new gadgets, shiny new development frameworks, or reminisce about crusty old technology that haunts his past.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/5950304?v=3

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: joelhulen
  instagram:
  linkedin: joelhulen
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: joelhulen
  stackoverflow: # users/<numeric_id>/<user_name>
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
